{
 "title": "Fotowoltaika",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "BMS Diagnostyka", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Napięcia Celi #1",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Ω",
     "query": "SELECT \"value\"\nFROM \"homeassistant\".\"autogen\".\"V\"\nWHERE \"entity_id\" =~ /esp32_pv_bms_cell_voltage_(0[1-9]|1[0-6])$/\n  AND $timeFilter\nGROUP BY \"entity_id\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "entity_id::tag",
       "operator": "=",
       "value": "jk_bms_nx_jk_bms_1_cell_resistance_1"
      }
     ]
    }
   ]
  },
  {
   "title": "Napięcia Celi #1",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "measurement": "Ω",
     "query": "SELECT \"value\"\nFROM \"homeassistant\".\"autogen\".\"V\"\nWHERE \"entity_id\" =~ /esp32_pv_bms_cell_voltage_(0[1-9]|1[0-6])$/\n  AND $timeFilter\nGROUP BY \"entity_id\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "entity_id::tag",
       "operator": "=",
       "value": "jk_bms_nx_jk_bms_1_cell_resistance_1"
      }
     ]
    }
   ]
  },
  {
   "title": "Średnie napięcie Cel",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Ω",
     "query": "SELECT \"value\"\nFROM \"homeassistant\".\"autogen\".\"V\"\nWHERE \"entity_id\"='esp32_pv_bms_average_cell_voltage'\n  AND $timeFilter\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "entity_id::tag",
       "operator": "=",
       "value": "jk_bms_nx_jk_bms_1_cell_resistance_1"
      }
     ]
    }
   ]
  },
  {
   "title": "Średnie napięcie Cel",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 18, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "measurement": "Ω",
     "query": "SELECT \"value\"\nFROM \"homeassistant\".\"autogen\".\"V\"\nWHERE \"entity_id\"='esp32_pv_bms_average_cell_voltage'\n  AND $timeFilter\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "entity_id::tag",
       "operator": "=",
       "value": "jk_bms_nx_jk_bms_1_cell_resistance_1"
      }
     ]
    }
   ]
  },
  {
   "title": "Delta napięć celi",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT \"value\"\nFROM \"homeassistant\".\"autogen\".\"V\"\nWHERE (\"entity_id\" = 'esp32_pv_bms_delta_cell_voltage')\n  AND $timeFilter\nGROUP BY \"entity_id\"\n"
    }
   ]
  },
  {
   "title": "SoC",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT \"value\"\nFROM \"homeassistant\".\"autogen\".\"%\"\nWHERE (\"entity_id\" = 'esp32_pv_bms_state_of_charge')\n  AND $timeFilter\nGROUP BY \"entity_id\"\n"
    }
   ]
  },
  {
   "title": "SoC",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "SoC",
     "query": "SELECT \"value\"\nFROM \"homeassistant\".\"autogen\".\"%\"\nWHERE (\"entity_id\" = 'esp32_pv_bms_state_of_charge')\n  AND $timeFilter\nGROUP BY \"entity_id\"\n"
    }
   ]
  },
  {
   "title": "Całkowite napięcie baterii",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT \"value\"\nFROM \"homeassistant\".\"autogen\".\"V\"\nWHERE (\"entity_id\" = 'esp32_pv_bms_total_voltage')\n  AND $timeFilter\nGROUP BY \"entity_id\"\n"
    }
   ]
  },
  {
   "title": "Całkowite napięcie baterii",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 6, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "Napięcie",
     "query": "SELECT \"value\"\nFROM \"homeassistant\".\"autogen\".\"V\"\nWHERE (\"entity_id\" = 'esp32_pv_bms_total_voltage')\nAND $timeFilter\n\n"
    }
   ]
  },
  {
   "title": "Rezystancja Celi",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "ohm" } },
   "targets": [
    {
     "measurement": "Ω",
     "query": "SELECT \"value\"\nFROM \"homeassistant\".\"autogen\".\"Ω\"\nWHERE (\"entity_id\" =~ /esp32_pv_bms_cell_resistance_(\\d{1,2})$/)\n  AND $timeFilter\nGROUP BY \"entity_id\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "entity_id::tag",
       "operator": "=",
       "value": "jk_bms_nx_jk_bms_1_cell_resistance_1"
      }
     ]
    }
   ]
  },
  {
   "title": "Temperatury",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "measurement": "Ω",
     "query": "SELECT \"value\"\nFROM \"homeassistant\".\"autogen\".\"°C\"\nWHERE (\"entity_id\" =~ /esp32_pv_bms_temperature_sensor_(\\d{1})$/) OR \"entity_id\"='esp32_pv_bms_power_tube_temperature'\n  AND $timeFilter\nGROUP BY \"entity_id\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "entity_id::tag",
       "operator": "=",
       "value": "jk_bms_nx_jk_bms_1_cell_resistance_1"
      }
     ]
    }
   ]
  },
  { "title": "Moc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Moc",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "BMS",
     "query": "SELECT \"value\"\nFROM \"homeassistant\".\"autogen\".\"W\"\nWHERE (\"entity_id\" = 'esp32_pv_bms_power')\n  AND $timeFilter"
    },
    {
     "alias": "PV* Wejściowa",
     "query": "SELECT \"value\"\nFROM \"homeassistant\".\"autogen\".\"W\"\nWHERE (\"entity_id\" =~ /growat_esp_growatt_pv\\d{1}_power/)\n  AND $timeFilter"
    },
    {
     "alias": "Falownik Wyjściowa",
     "query": "SELECT \"value\"\nFROM \"homeassistant\".\"autogen\".\"W\"\nWHERE (\"entity_id\" ='growat_esp_growatt_output_active_power')\n  AND $timeFilter"
    }
   ]
  },
  {
   "title": "Moc w czasie",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 6, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "BMS",
     "query": "SELECT  \"value\"\nFROM \"homeassistant\".\"autogen\".\"W\"\nWHERE (\"entity_id\" = 'esp32_pv_bms_power')\n  AND $timeFilter\n"
    },
    {
     "alias": "PV*",
     "query": "SELECT \"value\"\nFROM \"homeassistant\".\"autogen\".\"W\"\nWHERE (\"entity_id\" =~ /growat_esp_growatt_pv\\d{1}_power/)\n  AND $timeFilter"
    },
    {
     "alias": "Falownik Wyjściowa",
     "query": "SELECT \"value\"\nFROM \"homeassistant\".\"autogen\".\"W\"\nWHERE (\"entity_id\" ='growat_esp_growatt_output_active_power')\n  AND $timeFilter"
    }
   ]
  },
  { "title": "Natężenie", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Natężenie",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "BMS",
     "query": "SELECT \"value\"\nFROM \"homeassistant\".\"autogen\".\"A\"\nWHERE (\"entity_id\" = 'esp32_pv_bms_current')\n  AND $timeFilter"
    },
    {
     "alias": "PV* Wejściowa",
     "query": "SELECT \"value\"\nFROM \"homeassistant\".\"autogen\".\"A\"\nWHERE (\"entity_id\" =~ /growat_esp_growatt_pv\\d{1}_current/)\n  AND $timeFilter"
    },
    {
     "alias": "Falownik Wyjściowa",
     "query": "SELECT \"value\"\nFROM \"homeassistant\".\"autogen\".\"A\"\nWHERE (\"entity_id\" ='growat_esp_growatt_output_current')\n  AND $timeFilter"
    }
   ]
  },
  {
   "title": "Natężenie w czasie",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 6, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "alias": "BMS",
     "query": "SELECT \"value\"\nFROM \"homeassistant\".\"autogen\".\"A\"\nWHERE (\"entity_id\" = 'esp32_pv_bms_current')\n  AND $timeFilter"
    },
    {
     "alias": "PV* Wejściowa",
     "query": "SELECT \"value\"\nFROM \"homeassistant\".\"autogen\".\"A\"\nWHERE (\"entity_id\" =~ /growat_esp_growatt_pv\\d{1}_current/)\n  AND $timeFilter"
    },
    {
     "alias": "Falownik Wyjściowa",
     "query": "SELECT \"value\"\nFROM \"homeassistant\".\"autogen\".\"A\"\nWHERE (\"entity_id\" ='growat_esp_growatt_output_current')\n  AND $timeFilter"
    }
   ]
  },
  { "title": "PV", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 } },
  {
   "title": "Napięcie",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "PV* Wejściowa",
     "query": "SELECT \"value\"\nFROM \"homeassistant\".\"autogen\".\"V\"\nWHERE (\"entity_id\" =~ /growat_esp_growatt_pv\\d{1}_voltage/)\n  AND $timeFilter"
    },
    {
     "alias": "Falownik Wyjściowa",
     "query": "SELECT \"value\"\nFROM \"homeassistant\".\"autogen\".\"V\"\nWHERE (\"entity_id\" ='growat_esp_growatt_ac_output_voltage')\n  AND $timeFilter"
    }
   ]
  },
  {
   "title": "Napięcie w czasie",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 6, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "PV* Wejściowa",
     "query": "SELECT \"value\"\nFROM \"homeassistant\".\"autogen\".\"V\"\nWHERE (\"entity_id\" =~ /growat_esp_growatt_pv\\d{1}_voltage/)\n  AND $timeFilter"
    },
    {
     "alias": "Falownik Wyjściowa",
     "query": "SELECT \"value\"\nFROM \"homeassistant\".\"autogen\".\"V\"\nWHERE (\"entity_id\" ='growat_esp_growatt_ac_output_voltage')\n  AND $timeFilter"
    }
   ]
  },
  {
   "title": "Prędkość wentylatorów",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT \"value\"\nFROM \"homeassistant\".\"autogen\".\"%\"\nWHERE (\n  \"entity_id\" = 'growat_esp_growatt_inverter_fan_speed' OR \n  \"entity_id\" = 'growat_esp_growatt_mppt_fan_speed'\n)\nAND $timeFilter\nGROUP BY \"entity_id\"\n\n"
    }
   ]
  },
  {
   "title": "Obciążenie Falownika",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT \"value\"\nFROM \"homeassistant\".\"autogen\".\"%\"\nWHERE (\"entity_id\" = 'growat_esp_growatt_load_percentage')\n  AND $timeFilter\nGROUP BY \"entity_id\"\n"
    }
   ]
  },
  {
   "title": "Temperatury",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "measurement": "Ω",
     "query": "SELECT \"value\"\nFROM \"homeassistant\".\"autogen\".\"°C\"\nWHERE (\"entity_id\" =~ /growat_esp_growatt_buck_\\d{1}_temperature/) \n  OR \"entity_id\" = 'growat_esp_growatt_dc_dc_temperature'\n    OR \"entity_id\" = 'growat_esp_growatt_inverter_temperature'\n    OR \"entity_id\" = 'growat_esp_growatt_pv_temperature'\n  AND $timeFilter\nGROUP BY \"entity_id\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "entity_id::tag",
       "operator": "=",
       "value": "jk_bms_nx_jk_bms_1_cell_resistance_1"
      }
     ]
    }
   ]
  }
 ]
}