substitutions:
  name: jk-bms
  bms0: "${name}_1"
  device_description: "Monitor and control a JK-BMS v11 via bluetooth"
  external_components_source: github://syssi/esphome-jk-bms@main
  bms0_mac_address: #insert bms mac address
  bms0_protocol_version: #refer to https://github.com/syssi/esphome-jk-bms

esphome:
  name: ${name}-nx
  comment: ${device_description}
  min_version: 2024.6.0
  project:
    name: "syssi.esphome-jk-bms"
    version: 2.1.0

  on_boot:
    priority: -100
    then:
      - component.update: bms0_mac_text
      - text_sensor.template.publish:
          id: esp_status
          state: "Normal"  

esp32:
  board: esp32dev
  framework:
    type: esp-idf

external_components:
  - source: ${external_components_source}
    refresh: 0s

wifi:

  ssid: !secret wifi_ssid
  password: !secret wifi_password


ota:
  platform: esphome
  on_begin:
    then:
      - switch.turn_off: ble_client_switch0
      - logger.log: "BLE connection suspended for OTA update"

logger:
  level: WARN

api:

esp32_ble_tracker:
  scan_parameters:
    active: false
    interval: 1500ms
    window: 300ms

ble_client:

# Master(1)  
  - mac_address: ${bms0_mac_address}
    id: client0

jk_bms_ble:

# Master(1)  
  - ble_client_id: client0
    protocol_version: ${bms0_protocol_version}
    throttle: 3s
    id: bms0
      

light:
  - platform: monochromatic
    output: WIFI_LED
    id: status_led
    default_transition_length: 0s
    effects:
      - pulse:
          name: "Slow Pulse"
          transition_length: 2s
          update_interval: 2s
      - pulse:
          name: "Fast Pulse"
          transition_length: 0.5s
          update_interval: 0.5s

output:
  - platform: ledc
    pin: GPIO2
    id: WIFI_LED 

binary_sensor:


# Master(1)  
  - platform: jk_bms_ble  
    jk_bms_ble_id: bms0
    balancing:
      name: "${bms0} balancing"
    charging:
      name: "${bms0} charging"
    discharging:
      name: "${bms0} discharging"

button:


# Master(1)
  - platform: jk_bms_ble  
    jk_bms_ble_id: bms0
    retrieve_settings:
      name: "${bms0} retrieve settings"
      id: retrieve_resistance_bms0
    retrieve_device_info:
      name: "${bms0} retrieve device info"


number:

# Master(1) 
  - platform: jk_bms_ble 
    jk_bms_ble_id: bms0
    balance_starting_voltage:
      name: "${bms0} balance starting voltage"

sensor:

# Free RAM
  - platform: template
    name: "${name} Free RAM"
    lambda: "return (float)esp_get_free_heap_size() / 1024.0;"
    update_interval: 10s
    unit_of_measurement: "kB"
    accuracy_decimals: 1
    entity_category: diagnostic  

# Wifi signal Strenght
  - platform: wifi_signal
    name: "WiFi signal strenght"
    update_interval: 10s       

# Sumaryczna moc (W)
  - platform: template
    name: "Total power"
    id: Laczna_moc
    unit_of_measurement: "W"
    state_class: measurement
    accuracy_decimals: 0
    update_interval: 5s
    lambda: |-
      return id(LFP_1_moc).state; 


# Sumaryczna moc oddana (W)
  - platform: template
    name: "Total discharging power"
    id: Laczna_moc_oddawana
    unit_of_measurement: "W"
    state_class: measurement
    accuracy_decimals: 0
    update_interval: 5s
    lambda: |-
      return id(LFP_1_oddanie).state;
    

# Sumaryczna moc przyjęta (W)
  - platform: template
    name: "Total Charging power"
    id: Laczna_moc_przyjmowana
    unit_of_measurement: "W"
    state_class: measurement
    accuracy_decimals: 0
    update_interval: 5s
    lambda: |-
      return id(LFP_1_przyjecie).state; 


# Całkowita energia oddana przez cały system (kWh)
  - platform: integration
    name: "LFP discharging total"
    sensor: Laczna_moc_oddawana
    time_unit: h
    restore: true
    icon: mdi:counter
    state_class: total_increasing
    device_class: energy
    accuracy_decimals: 2
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh  

# Całkowita energia przyjęta przez cały system (kWh)
  - platform: integration
    name: "LFP charging total"
    sensor: Laczna_moc_przyjmowana
    time_unit: h
    restore: true
    icon: mdi:counter
    state_class: total_increasing
    device_class: energy
    accuracy_decimals: 2
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh  

# Energia oddana dzisiaj dla całego systemu
  - platform: total_daily_energy
    name: "LFP discharging today"
    restore: true
    icon: mdi:counter
    power_id: Laczna_moc_oddawana
    accuracy_decimals: 2
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh
    device_class: energy 

# Energia przyjęta dzisiaj dla całego systemu
  - platform: total_daily_energy
    name: "LFP charging today"
    restore: true
    icon: mdi:counter
    power_id: Laczna_moc_przyjmowana
    accuracy_decimals: 2
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh
    device_class: energy 

# Master(1) 
  - platform: jk_bms_ble 
    jk_bms_ble_id: bms0
    min_voltage_cell:
      name: "${bms0} min voltage cell"
    max_voltage_cell:
      name: "${bms0} max voltage cell"
    delta_cell_voltage:
      name: "${bms0} delta cell voltage"
    average_cell_voltage:
      name: "${bms0} average cell voltage"
    cell_voltage_1:
      name: "${bms0} cell voltage 01"
    cell_voltage_2:
      name: "${bms0} cell voltage 02"
    cell_voltage_3:
      name: "${bms0} cell voltage 03"
    cell_voltage_4:
      name: "${bms0} cell voltage 04"
    cell_voltage_5:
      name: "${bms0} cell voltage 05"
    cell_voltage_6:
      name: "${bms0} cell voltage 06"
    cell_voltage_7:
      name: "${bms0} cell voltage 07"
    cell_voltage_8:
      name: "${bms0} cell voltage 08"
    cell_voltage_9:
      name: "${bms0} cell voltage 09"
    cell_voltage_10:
      name: "${bms0} cell voltage 10"
    cell_voltage_11:
      name: "${bms0} cell voltage 11"
    cell_voltage_12:
      name: "${bms0} cell voltage 12"
    cell_voltage_13:
      name: "${bms0} cell voltage 13"
    cell_voltage_14:
      name: "${bms0} cell voltage 14"
    cell_voltage_15:
      name: "${bms0} cell voltage 15"
    cell_voltage_16:
      name: "${bms0} cell voltage 16"

    cell_resistance_1:
      name: "${bms0} cell resistance 01"
    cell_resistance_2:
      name: "${bms0} cell resistance 02"
    cell_resistance_3:
      name: "${bms0} cell resistance 03"
    cell_resistance_4:
      name: "${bms0} cell resistance 04"
    cell_resistance_5:
      name: "${bms0} cell resistance 05"
    cell_resistance_6:
      name: "${bms0} cell resistance 06"
    cell_resistance_7:
      name: "${bms0} cell resistance 07"
    cell_resistance_8:
      name: "${bms0} cell resistance 08"
    cell_resistance_9:
      name: "${bms0} cell resistance 09"
    cell_resistance_10:
      name: "${bms0} cell resistance 10"
    cell_resistance_11:
      name: "${bms0} cell resistance 11"
    cell_resistance_12:
      name: "${bms0} cell resistance 12"
    cell_resistance_13:
      name: "${bms0} cell resistance 13"
    cell_resistance_14:
      name: "${bms0} cell resistance 14"
    cell_resistance_15:
      name: "${bms0} cell resistance 15"
    cell_resistance_16:
      name: "${bms0} cell resistance 16"    
    total_voltage:
      name: "${bms0} total voltage"
    current:
      name: "${bms0} current"
    power:
      name: "${bms0} power"
      id: LFP_1_moc
    charging_power:
      name: "${bms0} charging power"
      id: LFP_1_przyjecie
    discharging_power:
      name: "${bms0} discharging power"
      id: LFP_1_oddanie
    temperature_sensor_1:
      name: "${bms0} temperature sensor 1"
    temperature_sensor_2:
      name: "${bms0} temperature sensor 2"
    temperature_sensor_3:
      name: "${bms0} temperature sensor 3"
    temperature_sensor_4:
      name: "${bms0} temperature sensor 4"
    power_tube_temperature:
      name: "${bms0} power tube temperature"
    state_of_charge:
      name: "${bms0} state of charge"
    capacity_remaining:
      name: "${bms0} capacity remaining"
    total_battery_capacity_setting:
      name: "${bms0} total battery capacity setting"
    charging_cycles:
      name: "${bms0} charging cycles"
    total_charging_cycle_capacity:
      name: "${bms0} total charging cycle capacity"
    balancing_current:
      name: "${bms0} balancing current"


switch:
  # Restart Switch
  - platform: restart
    name: "jk_bms_connector_Restart"    

# Master(1) 
  - platform: jk_bms_ble 
    jk_bms_ble_id: bms0
    charging:
      name: "${bms0} charging"
    discharging:
      name: "${bms0} discharging"


# Master(1)
  - platform: ble_client  
    ble_client_id: client0
    id: ble_client_switch0
    name: "${bms0} enable bluetooth connection"
 

text_sensor:

  - platform: template
    name: "Status"
    id: esp_status
    entity_category: diagnostic
    icon: mdi:information-outline
    update_interval: never

  # MAC Address
  - platform: template
    name: "${bms0} BLE"
    id: bms0_mac_text
    entity_category: diagnostic
    icon: mdi:bluetooth
    lambda: |-
      return {"${bms0_mac_address}"};
    update_interval: never

# Wifi Info
  - platform: wifi_info
    ip_address:
      name: "${name} IP"
    ssid:
      name: "${name} SSID"
    mac_address:
      name: "${name} MAC"

# Errors
  - platform: jk_bms_ble  
    jk_bms_ble_id: bms0
    errors:
      name: "${bms0} errors"
    total_runtime_formatted:
      name: "${bms0} total runtime formatted"

# Get Resistance
interval:
  - interval: 2h
    then:
      - logger.log: "BMS0 resistance update"
      - button.press: retrieve_resistance_bms0

# Blue Light control 
  - interval: 5s
    then:
      - if:
          condition:
            not:
              wifi.connected: {}
          then:
            - light.turn_on:
                id: status_led
                effect: "Slow Pulse"
          else:
            - if:
                condition:
                  not:
                    api.connected: {}
                then:
                  - light.turn_on:
                      id: status_led
                      effect: "Fast Pulse"
                else:
                  - light.turn_on:
                      id: status_led
                      brightness: 100%
                      effect: none

time:
  - platform: homeassistant
    id: homeassistant_time      
